### ISSUE TITLE
Ожидается ли поддержка Redmine 4.x

### ISSUE THREAD

**Issue by koren85** [nixys/nxs-chat-srv#22]
Не работает плагин на Redmine 4.х. Ошибки при запуске Redmine 4.0.4

**Comment by pauloriply** [comment]
> Не работает плагин на Redmine 4.х. Ошибки при запуске Redmine 4.0.4

Какая конкретно ошибка возникает на 4 версии редмайна?

**Comment by soulstorm10** [comment]
> > Не работает плагин на Redmine 4.х. Ошибки при запуске Redmine 4.0.4
> 
> Какая конкретно ошибка возникает на 4 версии редмайна?

Привет!
Так же получил ошибку при старте redmine4.
Версия Redmine (офф docker образ): 
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Mercurial                      4.8.2
  Bazaar                         2.8.0
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  no plugin installed

Текст ошибки:
`redmine_1  | NoMethodError: undefined method `alias_method_chain' for MailHandler:Class
redmine_1  | Did you mean?  alias_method
redmine_1  | /usr/local/bundle/gems/actionmailer-5.2.4.2/lib/action_mailer/base.rb:582:in `method_missing'
redmine_1  | /usr/src/redmine/plugins/nxs_chat/lib/mail_handler_patch.rb:26:in `block in included'
redmine_1  | /usr/src/redmine/plugins/nxs_chat/lib/mail_handler_patch.rb:25:in `class_eval'
redmine_1  | /usr/src/redmine/plugins/nxs_chat/lib/mail_handler_patch.rb:25:in `included'
redmine_1  | /usr/src/redmine/plugins/nxs_chat/lib/mail_handler_patch.rb:50:in `include'
redmine_1  | /usr/src/redmine/plugins/nxs_chat/lib/mail_handler_patch.rb:50:in `<top (required)>'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require' 
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:378:in `block in require_or_load'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:13:in `loading' 
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:37:in `load_interlock'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:356:in `require_or_load'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:334:in `depend_on'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:246:in `require_dependency'
redmine_1  | /usr/src/redmine/plugins/nxs_chat/init.rb:3:in `<top (required)>'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require' 
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
redmine_1  | /usr/src/redmine/lib/redmine/plugin.rb:181:in `block in load'
redmine_1  | /usr/src/redmine/lib/redmine/plugin.rb:172:in `each'
redmine_1  | /usr/src/redmine/lib/redmine/plugin.rb:172:in `load'
redmine_1  | /usr/src/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `block in load'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:663:in `block in load_config_initializer'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:662:in `load_config_initializer'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `each'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `block in <class:Engine>'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `each'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `tsort_each_child'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
redmine_1  | /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
redmine_1  | /usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
redmine_1  | Tasks: TOP => db:migrate => db:load_config => environment
redmine_1  | (See full trace by running task with --trace)`
